name: exchange-rate-telegram-bot
services:
  bot:
    image: ghcr.io/yurnov/xratebot:v0.8.0
    container_name: exchange-rate-bot
    volumes:
      - ./data:/bot/data
    env_file: .env
    restart: unless-stopped
