name: Lint Docker files

on:
  push:
    branches:
      - main
      - 'dev*'
  pull_request:
    branches:
      - main
      - 'dev*'

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
          ignore: DL3008,SC3009,DL3013

      - name: Lint docker-compose.yml
        uses: zavoloklom/docker-compose-linter@v1.0.0
        with:
          file: docker-compose.yml
