name: Run tests and build Docker image for development version
on:
  push:
    branches:
      - '!master'
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-tags: True

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          $(cat Dockerfile | grep "pip install" | cut -f2- -d " ")

      - name: Install pylint
        run: |
          python -m pip install pylint==3.0.3

      - name: Lint Python code
        run: |
          pylint --disable=R,C,W1203 bot/main.py

      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
          ignore: DL3008,SC3009,DL3013

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        # do this step only on push to main and do not run for pull request
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/development' }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image for development version and push to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          # push to registry when merge to development
          push: ${{ github.ref == 'refs/heads/development' }}
          no-cache: true
          tags: ghcr.io/yurnov/xratebot:dev

  
